### ISSUE TITLE
1.19.3 support.

### ISSUE THREAD

**Issue by kirmerk1** [Sydokiddo/auditory#26]
Basically title. Thanks!

**Comment by EysseW** [comment]
yes

**Comment by MrLoLf** [comment]
As GitHub hasn't auto closed it yet, you can clos it now. As my pull request #28 with the mod being ported to 1.19.3 has been accepted and merged.

**Comment by le0-VV** [comment]
accepted and merged but no 1.19.3 release yet tho, is there any chance you can release the 1.19.3 fork as a jar file pls?

**Comment by MrLoLf** [comment]
You can build it on your own, I won't publish a 1.19.3 jar of this mod, as I think she will publish it anyway. I haven't written with her about it, but it's her mod, so I think she should publish it and not me, even if this is published under the MIT license. Because she is still active, as you can see on my pull request, that got merged.
If you want to build it on your own, you have to get [IntelliJ](https://www.jetbrains.com/idea/download/?ij80pr#section=windows) or [Eclipse](https://www.eclipse.org/downloads/packages/release/2022-06/r/eclipse-ide-java-developers). For IntelliJ, you can download the Community version, as it is free and has all required features. After you have installed it, download this project from GitHub, extract it and open it in IntelliJ or Eclipse. Run the `build.gradle` file. After that, a window should pop up in IntelliJ or Eclipse called Gradle it might be different for Eclipse, as I only use IntelliJ. If you have done this, you want to click on build, as shown in the picture. After that, the built jar will be located under `auditory/build/libs/` you should use the non source version. Just put that jar in your `Mods` folder and it is supposed to work.
![image](https://user-images.githubusercontent.com/66185550/217886598-012c92cf-b758-4d7e-98d4-cd24585c06f8.png)

**Comment by le0-VV** [comment]
I’ll look in to those, thank you so much!

**Comment by EysseW** [comment]
You don't need any IDE. Just close the source code and run ".\gradlew build" on windows or "./gradlew build" on linux/Mac in your command line.

**Comment by EysseW** [comment]
In the cloned directory that is.

**Comment by sydneybeanmc** [comment]
1.19.3 update should be out soon! I do want to get a few new additions in before publishing to CurseForge/Modrinth but thank you so much to MrLoLf for getting it ported for me, saves me a lot of time!
